import {
  User,
  Employee,
  LeaveType,
  LeaveBalance,
  LeaveRequest,
  SalaryProfile,
  SalaryComponent,
  PayrollRecord,
  Notification,
  AuditLog,
  SystemSettings,
  Attendance,
  EmployeeDocument,
  EmployeeRemovalRequest,
  Department,
} from '../types';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-eng',
    name: 'Engineering',
    code: 'ENG',
    description: 'Core product software engineering, cloud infrastructure, and technical architecture.',
    headOfDepartment: 'DAYFLOW-MR2023-003',
    location: 'San Francisco HQ',
    budget: 450000,
    active: true,
    createdAt: '2023-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'dept-hr',
    name: 'Human Resources',
    code: 'HR',
    description: 'People operations, talent acquisition, workplace culture, and employee welfare.',
    headOfDepartment: 'DAYFLOW-SJ2023-002',
    location: 'San Francisco HQ',
    budget: 180000,
    active: true,
    createdAt: '2023-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'dept-prod',
    name: 'Product & Design',
    code: 'PROD',
    description: 'Product strategy, roadmap execution, UX/UI design systems, and customer research.',
    headOfDepartment: 'DAYFLOW-AL2023-004',
    location: 'San Francisco HQ',
    budget: 220000,
    active: true,
    createdAt: '2023-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'dept-fin',
    name: 'Finance & Accounts',
    code: 'FIN',
    description: 'Corporate finance, payroll auditing, tax compliance, and financial budget planning.',
    headOfDepartment: 'DAYFLOW-AM2023-001',
    location: 'New York Office',
    budget: 160000,
    active: true,
    createdAt: '2023-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'dept-ops',
    name: 'Operations & Sales',
    code: 'OPS',
    description: 'Business operations, client success management, partnerships, and revenue generation.',
    headOfDepartment: 'DAYFLOW-DK2023-006',
    location: 'San Francisco HQ',
    budget: 310000,
    active: true,
    createdAt: '2023-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'dept-mkt',
    name: 'Marketing',
    code: 'MKT',
    description: 'Demand generation, brand storytelling, developer advocacy, and global communications.',
    headOfDepartment: 'DAYFLOW-DK2023-006',
    location: 'Austin Hub',
    budget: 190000,
    active: true,
    createdAt: '2023-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'dept-qa',
    name: 'Quality Assurance',
    code: 'QA',
    description: 'Automated testing suites, release verification, and quality engineering standards.',
    headOfDepartment: 'DAYFLOW-EW2023-007',
    location: 'San Francisco HQ',
    budget: 140000,
    active: true,
    createdAt: '2023-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  companyName: 'Dayflow Technologies Inc.',
  companyPrefix: 'DAYFLOW',
  companyLogoUrl: '',
  workingDaysPerWeek: 5,
  dailyWorkingHours: 8,
  employeeIdFormat: 'PREFIX_NAME_YEAR_SEQ',
  defaultCurrency: 'INR',
  publicSignupEnabled: false,
  overtimeMultiplier: 1.5,
  fiscalYearStartMonth: 1,
};

export const INITIAL_LEAVE_TYPES: LeaveType[] = [
  {
    id: 'lt-pto',
    name: 'Paid Time Off',
    code: 'PAID_TIME_OFF',
    description: 'General paid annual vacation and personal time off.',
    annualAllocation: 20,
    isPaid: true,
    requiresAttachment: false,
    requiresApproval: true,
    active: true,
    color: '#0284c7',
  },
  {
    id: 'lt-sick',
    name: 'Sick Leave',
    code: 'SICK_LEAVE',
    description: 'Medical recuperation and health emergencies.',
    annualAllocation: 12,
    isPaid: true,
    requiresAttachment: true,
    requiresApproval: true,
    active: true,
    color: '#e11d48',
  },
  {
    id: 'lt-unpaid',
    name: 'Unpaid Leave',
    code: 'UNPAID_LEAVE',
    description: 'Extended personal leave without wage payment.',
    annualAllocation: 30,
    isPaid: false,
    requiresAttachment: false,
    requiresApproval: true,
    active: true,
    color: '#d97706',
  },
];

export const INITIAL_SALARY_COMPONENTS: SalaryComponent[] = [
  {
    id: 'sc-basic',
    name: 'Basic Salary',
    code: 'BASIC',
    type: 'EARNING',
    calculationMethod: 'PERCENTAGE',
    value: 50,
    percentageBase: 'MONTHLY_WAGE',
    isEarning: true,
    isDeduction: false,
    active: true,
    description: 'Core taxable component (50% of monthly base wage)',
  },
  {
    id: 'sc-hra',
    name: 'House Rent Allowance',
    code: 'HRA',
    type: 'EARNING',
    calculationMethod: 'PERCENTAGE',
    value: 20,
    percentageBase: 'MONTHLY_WAGE',
    isEarning: true,
    isDeduction: false,
    active: true,
    description: 'Housing allowance (20% of monthly base wage)',
  },
  {
    id: 'sc-std',
    name: 'Standard Allowance',
    code: 'STD_ALLOWANCE',
    type: 'EARNING',
    calculationMethod: 'PERCENTAGE',
    value: 10,
    percentageBase: 'MONTHLY_WAGE',
    isEarning: true,
    isDeduction: false,
    active: true,
    description: 'General monthly allowance (10% of wage)',
  },
  {
    id: 'sc-bonus',
    name: 'Performance Bonus',
    code: 'PERF_BONUS',
    type: 'EARNING',
    calculationMethod: 'FIXED_AMOUNT',
    value: 25000,
    percentageBase: 'MONTHLY_WAGE',
    isEarning: true,
    isDeduction: false,
    active: true,
    description: 'Monthly incentive milestone stipend',
  },
  {
    id: 'sc-lta',
    name: 'Leave Travel Allowance',
    code: 'LTA',
    type: 'EARNING',
    calculationMethod: 'FIXED_AMOUNT',
    value: 10000,
    percentageBase: 'MONTHLY_WAGE',
    isEarning: true,
    isDeduction: false,
    active: true,
    description: 'Travel benefits subsidy',
  },
  {
    id: 'sc-fixed',
    name: 'Fixed Special Allowance',
    code: 'FIXED_ALLOWANCE',
    type: 'EARNING',
    calculationMethod: 'FIXED_AMOUNT',
    value: 15000,
    percentageBase: 'MONTHLY_WAGE',
    isEarning: true,
    isDeduction: false,
    active: true,
    description: 'Discretionary recurring fixed allowance',
  },
  {
    id: 'sc-pf-emp',
    name: 'Provident Fund (Employee)',
    code: 'PF_EMPLOYEE',
    type: 'DEDUCTION',
    calculationMethod: 'PERCENTAGE',
    value: 12,
    percentageBase: 'BASIC_SALARY',
    isEarning: false,
    isDeduction: true,
    active: true,
    description: 'Mandatory employee retirement contribution (12% of Basic)',
  },
  {
    id: 'sc-ptax',
    name: 'Professional Tax',
    code: 'PROF_TAX',
    type: 'DEDUCTION',
    calculationMethod: 'FIXED_AMOUNT',
    value: 200,
    percentageBase: 'MONTHLY_WAGE',
    isEarning: false,
    isDeduction: true,
    active: true,
    description: 'State professional tax deduction',
  },
  {
    id: 'sc-pf-empr',
    name: 'Provident Fund (Employer)',
    code: 'PF_EMPLOYER',
    type: 'EMPLOYER_CONTRIBUTION',
    calculationMethod: 'PERCENTAGE',
    value: 12,
    percentageBase: 'BASIC_SALARY',
    isEarning: false,
    isDeduction: false,
    active: true,
    description: 'Matching employer retirement reserve',
  },
];

export const DEMO_USERS: User[] = [
  {
    uid: 'demo-admin-uid',
    employeeId: 'DAYFLOW-AM2023-001',
    loginId: 'Admin',
    email: 'admin@demo.dayflow.local',
    role: 'ADMIN',
    status: 'ACTIVE',
    createdAt: '2023-01-10T08:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
    emailVerified: true,
  },
  {
    uid: 'demo-hr-uid',
    employeeId: 'DAYFLOW-SJ2023-002',
    loginId: 'HR',
    email: 'hr@demo.dayflow.local',
    role: 'HR',
    status: 'ACTIVE',
    createdAt: '2023-03-15T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
    emailVerified: true,
  },
  {
    uid: 'demo-emp-uid',
    employeeId: 'DAYFLOW-DC2024-003',
    loginId: 'OIJODO20240001',
    email: 'employee@demo.dayflow.local',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
    emailVerified: true,
  },
  {
    uid: 'demo-emp-2',
    employeeId: 'DAYFLOW-ER2024-004',
    loginId: 'OIELRO20240002',
    email: 'elena.rostova@demo.dayflow.local',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    createdAt: '2024-04-10T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
    emailVerified: true,
  },
  {
    uid: 'demo-emp-3',
    employeeId: 'DAYFLOW-MV2024-005',
    loginId: 'OIMAVA20240003',
    email: 'marcus.vance@demo.dayflow.local',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    createdAt: '2024-06-01T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
    emailVerified: true,
  },
  {
    uid: 'demo-emp-4',
    employeeId: 'DAYFLOW-PP2025-006',
    loginId: 'OIPRPA20250004',
    email: 'priya.patel@demo.dayflow.local',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    createdAt: '2025-01-15T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
    emailVerified: true,
  },
  {
    uid: 'demo-emp-5',
    employeeId: 'DAYFLOW-JT2025-007',
    loginId: 'OIJOTA20250005',
    email: 'jordan.taylor@demo.dayflow.local',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    createdAt: '2025-03-01T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
    emailVerified: true,
  },
];

export const DEMO_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    uid: 'demo-admin-uid',
    employeeId: 'DAYFLOW-AM2023-001',
    loginId: 'Admin',
    password: 'password @2026',
    firstName: 'Alex',
    lastName: 'Morgan',
    fullName: 'Alex Morgan',
    email: 'admin@demo.dayflow.local',
    phone: '+1 (555) 234-5678',
    profilePictureUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1988-04-12',
    address: '742 Evergreen Terrace, Suite 400, San Francisco, CA',
    nationality: 'American',
    gender: 'FEMALE',
    maritalStatus: 'MARRIED',
    dateOfJoining: '2023-01-10',
    company: 'Dayflow Technologies Inc.',
    department: 'Human Resources & Executive',
    designation: 'VP of People & Operations',
    manager: 'Board of Directors',
    location: 'San Francisco HQ',
    employmentStatus: 'ACTIVE',
    bankDetails: {
      accountNumber: '987654321098',
      bankName: 'Silicon Valley Commercial Bank',
      ifscCode: 'SVCB0001042',
      panNumber: 'ALXM9821K',
      uanNumber: '100982341120',
      empCode: 'EMP-ADM-001',
    },
    aboutMe: 'Leading organizational development, HR strategy, workforce management, and cultural operations at Dayflow Technologies.',
    jobHighlights: 'Architected company-wide performance framework, scaling operations from 20 to 250+ employees.',
    interests: 'Marathon running, vintage photography, organizational psychology.',
    skills: ['Strategic HR', 'Executive Leadership', 'Workforce Planning', 'Compensation Structuring'],
    certifications: ['SHRM-SCP Senior Certified Professional', 'Executive Leadership Certificate (Stanford)'],
    createdAt: '2023-01-10T08:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'emp-2',
    uid: 'demo-hr-uid',
    employeeId: 'DAYFLOW-SJ2023-002',
    loginId: 'HR',
    password: 'password @2026',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    fullName: 'Sarah Jenkins',
    email: 'hr@demo.dayflow.local',
    phone: '+1 (555) 345-6789',
    profilePictureUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1992-09-24',
    address: '120 Market Street, Apt 8B, San Francisco, CA',
    nationality: 'American',
    gender: 'FEMALE',
    maritalStatus: 'SINGLE',
    dateOfJoining: '2023-03-15',
    company: 'Dayflow Technologies Inc.',
    department: 'Human Resources',
    designation: 'Senior HR Manager',
    manager: 'Alex Morgan',
    location: 'San Francisco HQ',
    employmentStatus: 'ACTIVE',
    bankDetails: {
      accountNumber: '876543210987',
      bankName: 'First Republic Bank',
      ifscCode: 'FRBK0008891',
      panNumber: 'SRHJ4421M',
      uanNumber: '100445671190',
      empCode: 'EMP-HR-002',
    },
    aboutMe: 'Passionate about talent development, employee engagement, fair payroll administration, and workplace happiness.',
    jobHighlights: 'Spearheaded employee onboarding enhancement and modernized time-off approval flows.',
    interests: 'Ceramics, cycling along Embarcadero, reading modern fiction.',
    skills: ['Talent Acquisition', 'HR Analytics', 'Employee Relations', 'Payroll Compliance'],
    certifications: ['PHR Professional in Human Resources', 'Agile HR Certified Practitioner'],
    createdAt: '2023-03-15T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'emp-3',
    uid: 'demo-emp-uid',
    employeeId: 'DAYFLOW-DC2024-003',
    loginId: 'OIJODO20240001',
    password: 'password @2026',
    firstName: 'David',
    lastName: 'Chen',
    fullName: 'David Chen',
    email: 'employee@demo.dayflow.local',
    phone: '+1 (555) 456-7890',
    profilePictureUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1995-11-03',
    address: '456 Mission Bay Blvd, Apt 12A, San Francisco, CA',
    nationality: 'American',
    gender: 'MALE',
    maritalStatus: 'SINGLE',
    dateOfJoining: '2024-02-01',
    company: 'Dayflow Technologies Inc.',
    department: 'Engineering',
    designation: 'Senior Full Stack Engineer',
    manager: 'Marcus Vance',
    location: 'San Francisco HQ',
    employmentStatus: 'ACTIVE',
    bankDetails: {
      accountNumber: '765432109876',
      bankName: 'Chase Manhattan Bank',
      ifscCode: 'CHAS0004512',
      panNumber: 'DVDC8823L',
      uanNumber: '100889230045',
      empCode: 'EMP-ENG-003',
    },
    aboutMe: 'Specializing in resilient cloud microservices, high-performance web frontends, and distributed systems architecture.',
    jobHighlights: 'Engineered sub-millisecond data sync pipelines and optimized responsive dashboard load metrics.',
    interests: 'Mechanical keyboards, indie game development, rock climbing.',
    skills: ['TypeScript', 'React', 'Node.js', 'PostgreSQL', 'Cloud Infrastructure'],
    certifications: ['AWS Certified Solutions Architect', 'Google Cloud Professional Cloud Architect'],
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'emp-4',
    uid: 'demo-emp-2',
    employeeId: 'DAYFLOW-ER2024-004',
    loginId: 'OIELRO20240002',
    password: 'password @2026',
    firstName: 'Elena',
    lastName: 'Rostova',
    fullName: 'Elena Rostova',
    email: 'elena.rostova@demo.dayflow.local',
    phone: '+1 (555) 567-8901',
    profilePictureUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1993-06-18',
    address: '890 Folsom Street, San Francisco, CA',
    nationality: 'Canadian',
    gender: 'FEMALE',
    maritalStatus: 'MARRIED',
    dateOfJoining: '2024-04-10',
    company: 'Dayflow Technologies Inc.',
    department: 'Design',
    designation: 'Lead Product Designer',
    manager: 'Alex Morgan',
    location: 'San Francisco HQ',
    employmentStatus: 'ACTIVE',
    bankDetails: {
      accountNumber: '654321098765',
      bankName: 'Wells Fargo Bank',
      ifscCode: 'WFBK0003310',
      panNumber: 'ELNR3319P',
      uanNumber: '100778891234',
      empCode: 'EMP-DSG-004',
    },
    aboutMe: 'Dedicated to designing intuitive, accessible, and delightful enterprise product experiences with cohesive design systems.',
    jobHighlights: 'Crafted the Dayflow unified component token library and accessibility guidelines.',
    interests: 'Typography collecting, botanical gardening, architectural sketch walks.',
    skills: ['Design Systems', 'Figma', 'User Research', 'Interaction Prototyping'],
    certifications: ['Nielsen Norman UX Master Certified', 'Interaction Design Foundation Member'],
    createdAt: '2024-04-10T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'emp-5',
    uid: 'demo-emp-3',
    employeeId: 'DAYFLOW-MV2024-005',
    loginId: 'OIMAVA20240003',
    password: 'password @2026',
    firstName: 'Marcus',
    lastName: 'Vance',
    fullName: 'Marcus Vance',
    email: 'marcus.vance@demo.dayflow.local',
    phone: '+1 (555) 678-9012',
    profilePictureUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1990-03-29',
    address: '321 Castro St, San Francisco, CA',
    nationality: 'American',
    gender: 'MALE',
    maritalStatus: 'MARRIED',
    dateOfJoining: '2024-06-01',
    company: 'Dayflow Technologies Inc.',
    department: 'Engineering',
    designation: 'Staff Infrastructure Architect',
    manager: 'Alex Morgan',
    location: 'Remote (US)',
    employmentStatus: 'ACTIVE',
    bankDetails: {
      accountNumber: '543210987654',
      bankName: 'Bank of America',
      ifscCode: 'BOFA0009941',
      panNumber: 'MRCV9902Q',
      uanNumber: '100665544321',
      empCode: 'EMP-ENG-005',
    },
    aboutMe: 'Scaling high-throughput distributed architectures, site reliability engineering, and zero-trust security postures.',
    jobHighlights: 'Maintained 99.995% service uptime and automated multi-region automated failover topology.',
    interests: 'Espresso roasting, astronomy, drone racing.',
    skills: ['Kubernetes', 'Terraform', 'Kafka', 'Zero-Trust Security', 'Go'],
    certifications: ['Certified Kubernetes Administrator (CKA)', 'HashiCorp Certified Terraform Associate'],
    createdAt: '2024-06-01T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'emp-6',
    uid: 'demo-emp-4',
    employeeId: 'DAYFLOW-PP2025-006',
    loginId: 'OIPRPA20250004',
    password: 'password @2026',
    firstName: 'Priya',
    lastName: 'Patel',
    fullName: 'Priya Patel',
    email: 'priya.patel@demo.dayflow.local',
    phone: '+1 (555) 789-0123',
    profilePictureUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1996-01-14',
    address: '150 California St, San Francisco, CA',
    nationality: 'Indian',
    gender: 'FEMALE',
    maritalStatus: 'SINGLE',
    dateOfJoining: '2025-01-15',
    company: 'Dayflow Technologies Inc.',
    department: 'Product Operations',
    designation: 'Product Operations Manager',
    manager: 'Sarah Jenkins',
    location: 'San Francisco HQ',
    employmentStatus: 'ACTIVE',
    bankDetails: {
      accountNumber: '432109876543',
      bankName: 'Standard Chartered Bank',
      ifscCode: 'SCBL0002100',
      panNumber: 'PRYP1104R',
      uanNumber: '100554433221',
      empCode: 'EMP-OPS-006',
    },
    aboutMe: 'Connecting product strategy with cross-functional execution and metrics-driven operational agility.',
    jobHighlights: 'Reduced quarterly sprint feedback loop delays by 40% using automated telemetry pipelines.',
    interests: 'Classical piano, trail running, board games.',
    skills: ['Product Operations', 'SQL', 'Mixpanel', 'Scrum Master', 'Jira'],
    certifications: ['Certified Scrum Product Owner (CSPO)', 'Pragmatic Institute Certified (PMC)'],
    createdAt: '2025-01-15T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'emp-7',
    uid: 'demo-emp-5',
    employeeId: 'DAYFLOW-JT2025-007',
    loginId: 'OIJOTA20250005',
    password: 'password @2026',
    firstName: 'Jordan',
    lastName: 'Taylor',
    fullName: 'Jordan Taylor',
    email: 'jordan.taylor@demo.dayflow.local',
    phone: '+1 (555) 890-1234',
    profilePictureUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1997-07-22',
    address: '500 Howard St, San Francisco, CA',
    nationality: 'American',
    gender: 'OTHER',
    maritalStatus: 'SINGLE',
    dateOfJoining: '2025-03-01',
    company: 'Dayflow Technologies Inc.',
    department: 'Quality Assurance',
    designation: 'QA Automation Lead',
    manager: 'Marcus Vance',
    location: 'San Francisco HQ',
    employmentStatus: 'ACTIVE',
    bankDetails: {
      accountNumber: '321098765432',
      bankName: 'Chase Bank',
      ifscCode: 'CHAS0007731',
      panNumber: 'JRDT7720S',
      uanNumber: '100443322110',
      empCode: 'EMP-QA-007',
    },
    aboutMe: 'Passionate about end-to-end automation, continuous integration testing, and software reliability.',
    jobHighlights: 'Automated 95% of regression test coverage across all major platform services.',
    interests: 'Synthesizers, sci-fi literature, photography.',
    skills: ['Playwright', 'Cypress', 'CI/CD Pipelines', 'Performance Testing'],
    certifications: ['ISTQB Advanced Level Test Automation Engineer'],
    createdAt: '2025-03-01T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
];

export const DEMO_SALARY_PROFILES: SalaryProfile[] = [
  {
    id: 'sp-1',
    employeeId: 'DAYFLOW-AM2023-001',
    monthlyWage: 145000,
    yearlyWage: 1740000,
    currency: 'INR',
    effectiveFrom: '2023-01-10',
    workingDaysPerWeek: 5,
    breakHours: 1,
    createdAt: '2023-01-10T08:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'sp-2',
    employeeId: 'DAYFLOW-SJ2023-002',
    monthlyWage: 95000,
    yearlyWage: 1140000,
    currency: 'INR',
    effectiveFrom: '2023-03-15',
    workingDaysPerWeek: 5,
    breakHours: 1,
    createdAt: '2023-03-15T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'sp-3',
    employeeId: 'DAYFLOW-DC2024-003',
    monthlyWage: 110000,
    yearlyWage: 1320000,
    currency: 'INR',
    effectiveFrom: '2024-02-01',
    workingDaysPerWeek: 5,
    breakHours: 1,
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'sp-4',
    employeeId: 'DAYFLOW-ER2024-004',
    monthlyWage: 105000,
    yearlyWage: 1260000,
    currency: 'INR',
    effectiveFrom: '2024-04-10',
    workingDaysPerWeek: 5,
    breakHours: 1,
    createdAt: '2024-04-10T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'sp-5',
    employeeId: 'DAYFLOW-MV2024-005',
    monthlyWage: 130000,
    yearlyWage: 1560000,
    currency: 'INR',
    effectiveFrom: '2024-06-01',
    workingDaysPerWeek: 5,
    breakHours: 1,
    createdAt: '2024-06-01T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'sp-6',
    employeeId: 'DAYFLOW-PP2025-006',
    monthlyWage: 80000,
    yearlyWage: 960000,
    currency: 'INR',
    effectiveFrom: '2025-01-15',
    workingDaysPerWeek: 5,
    breakHours: 1,
    createdAt: '2025-01-15T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'sp-7',
    employeeId: 'DAYFLOW-JT2025-007',
    monthlyWage: 85000,
    yearlyWage: 1020000,
    currency: 'INR',
    effectiveFrom: '2025-03-01',
    workingDaysPerWeek: 5,
    breakHours: 1,
    createdAt: '2025-03-01T09:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
];

export const DEMO_LEAVE_BALANCES: LeaveBalance[] = [
  // David Chen
  {
    id: 'lb-dc-pto',
    employeeId: 'DAYFLOW-DC2024-003',
    leaveTypeId: 'lt-pto',
    leaveTypeCode: 'PAID_TIME_OFF',
    leaveTypeName: 'Paid Time Off',
    year: 2026,
    allocated: 20,
    used: 4,
    pending: 2,
    remaining: 14,
  },
  {
    id: 'lb-dc-sick',
    employeeId: 'DAYFLOW-DC2024-003',
    leaveTypeId: 'lt-sick',
    leaveTypeCode: 'SICK_LEAVE',
    leaveTypeName: 'Sick Leave',
    year: 2026,
    allocated: 12,
    used: 1,
    pending: 0,
    remaining: 11,
  },
  {
    id: 'lb-dc-unpaid',
    employeeId: 'DAYFLOW-DC2024-003',
    leaveTypeId: 'lt-unpaid',
    leaveTypeCode: 'UNPAID_LEAVE',
    leaveTypeName: 'Unpaid Leave',
    year: 2026,
    allocated: 30,
    used: 0,
    pending: 0,
    remaining: 30,
  },
  // Sarah Jenkins
  {
    id: 'lb-sj-pto',
    employeeId: 'DAYFLOW-SJ2023-002',
    leaveTypeId: 'lt-pto',
    leaveTypeCode: 'PAID_TIME_OFF',
    leaveTypeName: 'Paid Time Off',
    year: 2026,
    allocated: 20,
    used: 6,
    pending: 0,
    remaining: 14,
  },
  {
    id: 'lb-sj-sick',
    employeeId: 'DAYFLOW-SJ2023-002',
    leaveTypeId: 'lt-sick',
    leaveTypeCode: 'SICK_LEAVE',
    leaveTypeName: 'Sick Leave',
    year: 2026,
    allocated: 12,
    used: 2,
    pending: 0,
    remaining: 10,
  },
  {
    id: 'lb-sj-unpaid',
    employeeId: 'DAYFLOW-SJ2023-002',
    leaveTypeId: 'lt-unpaid',
    leaveTypeCode: 'UNPAID_LEAVE',
    leaveTypeName: 'Unpaid Leave',
    year: 2026,
    allocated: 30,
    used: 0,
    pending: 0,
    remaining: 30,
  },
];

export const DEMO_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lr-101',
    employeeId: 'DAYFLOW-DC2024-003',
    employeeName: 'David Chen',
    employeeDepartment: 'Engineering',
    leaveTypeId: 'lt-pto',
    leaveTypeName: 'Paid Time Off',
    leaveTypeCode: 'PAID_TIME_OFF',
    startDate: '2026-09-14',
    endDate: '2026-09-15',
    numberOfDays: 2,
    remarks: 'Attending family wedding and travel commitments.',
    status: 'PENDING',
    createdAt: '2026-08-19T14:30:00Z',
    updatedAt: '2026-08-19T14:30:00Z',
  },
  {
    id: 'lr-102',
    employeeId: 'DAYFLOW-ER2024-004',
    employeeName: 'Elena Rostova',
    employeeDepartment: 'Design',
    leaveTypeId: 'lt-sick',
    leaveTypeName: 'Sick Leave',
    leaveTypeCode: 'SICK_LEAVE',
    startDate: '2026-08-18',
    endDate: '2026-08-18',
    numberOfDays: 1,
    remarks: 'Dental surgery and prescribed recovery.',
    status: 'APPROVED',
    reviewedBy: 'demo-hr-uid',
    reviewedByName: 'Sarah Jenkins',
    reviewedAt: '2026-08-18T09:15:00Z',
    reviewComment: 'Approved. Get well soon!',
    createdAt: '2026-08-17T20:00:00Z',
    updatedAt: '2026-08-18T09:15:00Z',
  },
  {
    id: 'lr-103',
    employeeId: 'DAYFLOW-MV2024-005',
    employeeName: 'Marcus Vance',
    employeeDepartment: 'Engineering',
    leaveTypeId: 'lt-pto',
    leaveTypeName: 'Paid Time Off',
    leaveTypeCode: 'PAID_TIME_OFF',
    startDate: '2026-08-10',
    endDate: '2026-08-12',
    numberOfDays: 3,
    remarks: 'Summer break camping trip.',
    status: 'APPROVED',
    reviewedBy: 'demo-admin-uid',
    reviewedByName: 'Alex Morgan',
    reviewedAt: '2026-08-08T11:00:00Z',
    reviewComment: 'Approved. Enjoy the trip!',
    createdAt: '2026-08-07T10:00:00Z',
    updatedAt: '2026-08-08T11:00:00Z',
  },
  {
    id: 'lr-104',
    employeeId: 'DAYFLOW-PP2025-006',
    employeeName: 'Priya Patel',
    employeeDepartment: 'Product Operations',
    leaveTypeId: 'lt-unpaid',
    leaveTypeName: 'Unpaid Leave',
    leaveTypeCode: 'UNPAID_LEAVE',
    startDate: '2026-08-25',
    endDate: '2026-08-26',
    numberOfDays: 2,
    remarks: 'Relocation assistance for family.',
    status: 'PENDING',
    createdAt: '2026-08-20T16:00:00Z',
    updatedAt: '2026-08-20T16:00:00Z',
  },
];

export const DEMO_ATTENDANCE: Attendance[] = [
  {
    id: 'att-dc-20260821',
    employeeId: 'DAYFLOW-DC2024-003',
    date: '2026-08-21',
    checkIn: '2026-08-21T09:02:00Z',
    checkOut: null,
    breakStart: null,
    breakEnd: null,
    totalBreakMinutes: 0,
    workHours: 0,
    extraHours: 0,
    status: 'PRESENT',
    attendanceSource: 'WEB_CHECK_IN',
    remarks: 'Checked in on time via web dashboard',
    createdAt: '2026-08-21T09:02:00Z',
    updatedAt: '2026-08-21T09:02:00Z',
  },
  {
    id: 'att-dc-20260820',
    employeeId: 'DAYFLOW-DC2024-003',
    date: '2026-08-20',
    checkIn: '2026-08-20T08:55:00Z',
    checkOut: '2026-08-20T17:45:00Z',
    totalBreakMinutes: 45,
    workHours: 8.08,
    extraHours: 0.08,
    status: 'PRESENT',
    attendanceSource: 'WEB_CHECK_IN',
    createdAt: '2026-08-20T08:55:00Z',
    updatedAt: '2026-08-20T17:45:00Z',
  },
  {
    id: 'att-dc-20260819',
    employeeId: 'DAYFLOW-DC2024-003',
    date: '2026-08-19',
    checkIn: '2026-08-19T09:15:00Z',
    checkOut: '2026-08-19T18:30:00Z',
    totalBreakMinutes: 45,
    workHours: 8.5,
    extraHours: 0.5,
    status: 'PRESENT',
    attendanceSource: 'WEB_CHECK_IN',
    createdAt: '2026-08-19T09:15:00Z',
    updatedAt: '2026-08-19T18:30:00Z',
  },
  {
    id: 'att-dc-20260818',
    employeeId: 'DAYFLOW-DC2024-003',
    date: '2026-08-18',
    checkIn: '2026-08-18T09:00:00Z',
    checkOut: '2026-08-18T17:30:00Z',
    totalBreakMinutes: 60,
    workHours: 7.5,
    extraHours: 0,
    status: 'PRESENT',
    attendanceSource: 'WEB_CHECK_IN',
    createdAt: '2026-08-18T09:00:00Z',
    updatedAt: '2026-08-18T17:30:00Z',
  },
  {
    id: 'att-dc-20260817',
    employeeId: 'DAYFLOW-DC2024-003',
    date: '2026-08-17',
    checkIn: '2026-08-17T08:50:00Z',
    checkOut: '2026-08-17T18:10:00Z',
    totalBreakMinutes: 50,
    workHours: 8.5,
    extraHours: 0.5,
    status: 'PRESENT',
    attendanceSource: 'WEB_CHECK_IN',
    createdAt: '2026-08-17T08:50:00Z',
    updatedAt: '2026-08-17T18:10:00Z',
  },
  // Elena attendance
  {
    id: 'att-er-20260821',
    employeeId: 'DAYFLOW-ER2024-004',
    date: '2026-08-21',
    checkIn: '2026-08-21T09:10:00Z',
    checkOut: null,
    workHours: 0,
    extraHours: 0,
    status: 'PRESENT',
    attendanceSource: 'WEB_CHECK_IN',
    createdAt: '2026-08-21T09:10:00Z',
    updatedAt: '2026-08-21T09:10:00Z',
  },
  // Marcus attendance
  {
    id: 'att-mv-20260821',
    employeeId: 'DAYFLOW-MV2024-005',
    date: '2026-08-21',
    checkIn: '2026-08-21T08:45:00Z',
    checkOut: null,
    workHours: 0,
    extraHours: 0,
    status: 'PRESENT',
    attendanceSource: 'WEB_CHECK_IN',
    createdAt: '2026-08-21T08:45:00Z',
    updatedAt: '2026-08-21T08:45:00Z',
  },
];

export const DEMO_DOCUMENTS: EmployeeDocument[] = [
  {
    id: 'doc-1',
    employeeId: 'DAYFLOW-DC2024-003',
    name: 'David_Chen_Resume_2024.pdf',
    documentType: 'RESUME',
    storageUrl: 'https://example.com/docs/David_Chen_Resume.pdf',
    fileSize: '240 KB',
    uploadedBy: 'demo-hr-uid',
    uploadedByName: 'Sarah Jenkins',
    uploadedAt: '2024-02-01T10:00:00Z',
    visibility: 'EMPLOYEE_VISIBLE',
  },
  {
    id: 'doc-2',
    employeeId: 'DAYFLOW-DC2024-003',
    name: 'Employment_Agreement_Signed.pdf',
    documentType: 'CONTRACT',
    storageUrl: 'https://example.com/docs/Employment_Agreement.pdf',
    fileSize: '1.2 MB',
    uploadedBy: 'demo-hr-uid',
    uploadedByName: 'Sarah Jenkins',
    uploadedAt: '2024-02-01T10:05:00Z',
    visibility: 'EMPLOYEE_VISIBLE',
  },
];

export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    recipientUserId: 'demo-emp-uid',
    type: 'LEAVE_APPROVED',
    title: 'Leave Request Approved',
    message: 'Your Paid Time Off request for 2 days has been approved by Sarah Jenkins.',
    read: false,
    createdAt: '2026-08-18T10:00:00Z',
    relatedEntityId: 'lr-101',
    relatedEntityType: 'LEAVE',
  },
  {
    id: 'notif-2',
    recipientUserId: 'demo-admin-uid',
    type: 'LEAVE_SUBMITTED',
    title: 'New Leave Request',
    message: 'David Chen submitted a Paid Time Off request (2 days) for Sep 14-15, 2026.',
    read: false,
    createdAt: '2026-08-19T14:30:00Z',
    relatedEntityId: 'lr-101',
    relatedEntityType: 'LEAVE',
  },
  {
    id: 'notif-3',
    recipientUserId: 'demo-emp-uid',
    type: 'SALARY_UPDATED',
    title: 'July 2026 Payslip Ready',
    message: 'Your monthly payroll record for July 2026 is finalized and ready for viewing.',
    read: true,
    createdAt: '2026-08-01T09:00:00Z',
    relatedEntityId: 'pay-2026-07',
    relatedEntityType: 'PAYROLL',
  },
];

export const DEMO_REMOVAL_REQUESTS: EmployeeRemovalRequest[] = [
  {
    id: 'rem-req-1',
    employeeId: 'DAYFLOW-PP2025-006',
    employeeName: 'Priya Patel',
    employeeDepartment: 'Finance & Accounts',
    employeeDesignation: 'Financial Analyst',
    employeeEmail: 'priya.patel@demo.dayflow.local',
    reason: 'RESIGNATION',
    reasonDetails: 'Submitted voluntary 30-day notice to pursue international postgraduate studies in London.',
    proposedEffectiveDate: '2026-09-30',
    additionalNotes: 'Knowledge handover planned with senior accounting team. Clearance forms prepared.',
    status: 'PENDING',
    requestedByUid: 'demo-hr-uid',
    requestedByName: 'Sarah Jenkins',
    requestedByRole: 'HR',
    requestedAt: '2026-08-20T11:00:00Z',
    createdAt: '2026-08-20T11:00:00Z',
    updatedAt: '2026-08-20T11:00:00Z',
  },
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    actorUserId: 'demo-admin-uid',
    actorName: 'Alex Morgan',
    actorRole: 'ADMIN',
    action: 'EMPLOYEE_CREATED',
    entityType: 'Employee',
    entityId: 'DAYFLOW-JT2025-007',
    newValue: 'Created Jordan Taylor (QA Automation Lead)',
    timestamp: '2025-03-01T09:00:00Z',
  },
  {
    id: 'audit-2',
    actorUserId: 'demo-hr-uid',
    actorName: 'Sarah Jenkins',
    actorRole: 'HR',
    action: 'LEAVE_APPROVED',
    entityType: 'LeaveRequest',
    entityId: 'lr-102',
    previousValue: 'Status: PENDING',
    newValue: 'Status: APPROVED',
    timestamp: '2026-08-18T09:15:00Z',
  },
  {
    id: 'audit-3',
    actorUserId: 'demo-admin-uid',
    actorName: 'Alex Morgan',
    actorRole: 'ADMIN',
    action: 'SALARY_COMPONENT_UPDATED',
    entityType: 'SalaryComponent',
    entityId: 'sc-basic',
    newValue: 'Updated Basic Salary percentage base to 50%',
    timestamp: '2026-08-10T14:00:00Z',
  },
];


